apiVersion: v1
kind: Pod
metadata:
  name: testing-ns-pod
  namespace: restricted-ns
spec:
  volumes:
  - name: storage
    emptyDir: {}
  containers:
  - name: busybox
    image: busybox:1.28
    command: [ "sh", "-c", "sleep 1h" ]
    volumeMounts:
    - name: storage
      mountPath: /data/demo
      securityContext:
        privileged: true
