apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: frontend
  labels:
    env: test 
    tier: frontend
spec:
  # modify replicas according to your case
  replicas: 5
  selector:
    matchExpressions:
    - key: tier
      operator: In
      values: 
      - frontend
  template:
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
      - name: nginx
        image: quay.io/anshuk6469/mywebapp
