apiVersion: v1
kind: Pod
metadata:
  name: envvars-multiiple-secrets
  namespace: kiwi
spec:
  containers:
  - name: test
    image: nginx
    env:
    - name: USERKIWI
      valueFrom:
        secretKeyRef:
          name: juicysecret
          key: username
    - name: PASSKIWI
      valueFrom:
        secretKeyRef:
          name: juicysecret
          key: password

